apiVersion: v1
kind: Service
metadata:
  name: redis  # This is the "hostname" the backend will use
spec:
  selector:
    tier: cache
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379